"""
Pydantic models for questions.
"""

from typing import Optional, List
from pydantic import BaseModel, Field
from .interview import DifficultyLevel


class GeneratedQuestion(BaseModel):
    """A question generated by the AI for an interview session."""

    question_text: str
    category: str  # "behavioral", "technical", "system_design", "leadership"
    difficulty: DifficultyLevel
    related_resume_section: Optional[str] = None
    related_jd_requirement: Optional[str] = None
    rationale: Optional[str] = None  # why this question was chosen
    expected_skills: List[str] = Field(default_factory=list)


class QuestionBankItem(BaseModel):
    """A question from the static question bank."""

    question_id: str
    question_text: str
    interview_type: str
    category: str
    difficulty: int
    focus_areas: List[str] = Field(default_factory=list)
    custom_domain: Optional[str] = None
