export interface Question {
  id: string;
  text: string;
  category: string;
  difficulty: number;
  thinkingTime: number;
}

export interface Field {
  id: string;
  name: string;
  questions: Question[];
}

// Behavioral Questions (15 questions)
export const behavioralQuestions: Question[] = [
  {
    id: "b1",
    text: "Tell me about yourself and your background.",
    category: "Introduction",
    difficulty: 1,
    thinkingTime: 10,
  },
  {
    id: "b2",
    text: "Describe a challenging project you worked on and how you overcame obstacles.",
    category: "Experience",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "b3",
    text: "How do you handle working under pressure?",
    category: "Behavioral",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "b4",
    text: "What are your greatest strengths and how do they help you in your work?",
    category: "Strengths",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "b5",
    text: "Tell me about a time when you had to work with a difficult team member.",
    category: "Teamwork",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "b6",
    text: "Where do you see yourself in 5 years?",
    category: "Career Goals",
    difficulty: 2,
    thinkingTime: 10,
  },
  {
    id: "b7",
    text: "Describe a time when you failed and what you learned from it.",
    category: "Resilience",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "b8",
    text: "Tell me about a time when you had to make a difficult decision.",
    category: "Decision Making",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "b9",
    text: "How do you prioritize your work when you have multiple deadlines?",
    category: "Time Management",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "b10",
    text: "Describe a situation where you had to resolve a conflict between team members.",
    category: "Conflict Resolution",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "b11",
    text: "Tell me about a time when you went above and beyond for a project.",
    category: "Initiative",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "b12",
    text: "How do you handle constructive criticism?",
    category: "Feedback",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "b13",
    text: "Describe a time when you had to learn something new quickly.",
    category: "Learning",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "b14",
    text: "Tell me about a time when you had to persuade someone to see your point of view.",
    category: "Influence",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "b15",
    text: "What motivates you in your work?",
    category: "Motivation",
    difficulty: 1,
    thinkingTime: 30,
  },
];

// Technical Questions (15 questions)
export const technicalQuestions: Question[] = [
  {
    id: "t1",
    text: "Explain the difference between a stack and a queue. When would you use each?",
    category: "Data Structures",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "t2",
    text: "How would you optimize a slow database query?",
    category: "Database",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "t3",
    text: "Explain the concept of object-oriented programming and its main principles.",
    category: "OOP",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "t4",
    text: "How would you design a URL shortening service like bit.ly?",
    category: "System Design",
    difficulty: 4,
    thinkingTime: 90,
  },
  {
    id: "t5",
    text: "What is the difference between REST and GraphQL APIs?",
    category: "APIs",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "t6",
    text: "How would you handle memory leaks in a JavaScript application?",
    category: "Memory Management",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "t7",
    text: "Explain the concept of microservices architecture and its benefits.",
    category: "Architecture",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "t8",
    text: "How would you implement a caching strategy for a web application?",
    category: "Caching",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "t9",
    text: "What are the differences between SQL and NoSQL databases?",
    category: "Database",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "t10",
    text: "How would you ensure data consistency in a distributed system?",
    category: "Distributed Systems",
    difficulty: 4,
    thinkingTime: 90,
  },
  {
    id: "t11",
    text: "Explain the concept of version control and best practices for Git.",
    category: "Version Control",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "t12",
    text: "How would you approach debugging a production issue?",
    category: "Debugging",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "t13",
    text: "What is the difference between synchronous and asynchronous programming?",
    category: "Programming Concepts",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "t14",
    text: "How would you implement authentication and authorization in a web app?",
    category: "Security",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "t15",
    text: "Explain the concept of test-driven development (TDD).",
    category: "Testing",
    difficulty: 2,
    thinkingTime: 45,
  },
];

// Leadership Questions (15 questions)
export const leadershipQuestions: Question[] = [
  {
    id: "l1",
    text: "How do you motivate a team that's struggling with low morale?",
    category: "Team Motivation",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l2",
    text: "Describe a time when you had to make an unpopular decision for the good of the team.",
    category: "Decision Making",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l3",
    text: "How do you handle team members who consistently miss deadlines?",
    category: "Performance Management",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l4",
    text: "Tell me about a time when you had to lead a team through a major change.",
    category: "Change Management",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l5",
    text: "How do you balance being a leader and being a team player?",
    category: "Leadership Style",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "l6",
    text: "Describe a situation where you had to manage a team with diverse personalities.",
    category: "Team Dynamics",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l7",
    text: "How do you ensure your team understands and aligns with company goals?",
    category: "Alignment",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "l8",
    text: "Tell me about a time when you had to give difficult feedback to a team member.",
    category: "Feedback",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l9",
    text: "How do you delegate tasks effectively while ensuring quality?",
    category: "Delegation",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "l10",
    text: "Describe a time when you had to resolve a conflict between two key team members.",
    category: "Conflict Resolution",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l11",
    text: "How do you measure the success of your team?",
    category: "Performance Metrics",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "l12",
    text: "Tell me about a time when you had to step back and let someone else lead.",
    category: "Humble Leadership",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l13",
    text: "How do you develop talent within your team?",
    category: "Talent Development",
    difficulty: 2,
    thinkingTime: 45,
  },
  {
    id: "l14",
    text: "Describe a time when you had to pivot your team's strategy mid-project.",
    category: "Strategic Thinking",
    difficulty: 3,
    thinkingTime: 60,
  },
  {
    id: "l15",
    text: "How do you create a culture of innovation within your team?",
    category: "Innovation",
    difficulty: 3,
    thinkingTime: 60,
  },
];

// Custom Fields with specialized questions
export const customFields: Field[] = [
  {
    id: "product-manager",
    name: "Product Manager",
    questions: [
      {
        id: "pm1",
        text: "How do you prioritize features in a product roadmap?",
        category: "Product Strategy",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "pm2",
        text: "Describe your approach to user research and how it influences product decisions.",
        category: "User Research",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "pm3",
        text: "How do you handle competing stakeholder demands?",
        category: "Stakeholder Management",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "pm4",
        text: "Tell me about a time when you had to pivot a product strategy.",
        category: "Product Pivots",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "pm5",
        text: "How do you measure product success and what metrics do you use?",
        category: "Product Metrics",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "pm6",
        text: "Describe your experience with agile product development.",
        category: "Agile",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "pm7",
        text: "How do you balance user needs with business objectives?",
        category: "Balancing Priorities",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "pm8",
        text: "Tell me about a time when you had to say no to a feature request.",
        category: "Decision Making",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "pm9",
        text: "How do you approach competitive analysis?",
        category: "Market Analysis",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "pm10",
        text: "Describe your experience working with engineering teams.",
        category: "Cross-functional Collaboration",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "pm11",
        text: "How do you handle product launches and go-to-market strategies?",
        category: "Product Launch",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "pm12",
        text: "Tell me about a time when a product didn't meet expectations.",
        category: "Product Failure",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "pm13",
        text: "How do you approach A/B testing and experimentation?",
        category: "Experimentation",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "pm14",
        text: "Describe your approach to defining product requirements.",
        category: "Requirements",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "pm15",
        text: "How do you stay updated on industry trends and emerging technologies?",
        category: "Industry Knowledge",
        difficulty: 2,
        thinkingTime: 45,
      },
    ],
  },
  {
    id: "software-engineer",
    name: "Software Engineer",
    questions: [
      {
        id: "se1",
        text: "How do you approach code reviews and what do you look for?",
        category: "Code Quality",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "se2",
        text: "Describe your experience with different programming paradigms.",
        category: "Programming",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "se3",
        text: "How do you ensure your code is maintainable and scalable?",
        category: "Code Architecture",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se4",
        text: "Tell me about a complex technical problem you solved recently.",
        category: "Problem Solving",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se5",
        text: "How do you approach debugging complex issues?",
        category: "Debugging",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se6",
        text: "Describe your experience with different testing strategies.",
        category: "Testing",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "se7",
        text: "How do you stay updated with new technologies and frameworks?",
        category: "Learning",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "se8",
        text: "Tell me about a time when you had to refactor legacy code.",
        category: "Refactoring",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se9",
        text: "How do you handle performance optimization in your applications?",
        category: "Performance",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se10",
        text: "Describe your experience with DevOps and CI/CD practices.",
        category: "DevOps",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "se11",
        text: "How do you approach API design and what principles do you follow?",
        category: "API Design",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "se12",
        text: "Tell me about a time when you had to work with a difficult codebase.",
        category: "Legacy Systems",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se13",
        text: "How do you handle security considerations in your applications?",
        category: "Security",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se14",
        text: "Describe your approach to database design and optimization.",
        category: "Database",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "se15",
        text: "How do you collaborate with designers and product managers?",
        category: "Collaboration",
        difficulty: 2,
        thinkingTime: 45,
      },
    ],
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    questions: [
      {
        id: "ds1",
        text: "How do you approach data cleaning and preprocessing?",
        category: "Data Preparation",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ds2",
        text: "Describe your experience with different machine learning algorithms.",
        category: "ML Algorithms",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds3",
        text: "How do you validate the accuracy of your models?",
        category: "Model Validation",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds4",
        text: "Tell me about a data science project that had significant business impact.",
        category: "Business Impact",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds5",
        text: "How do you handle missing data in your datasets?",
        category: "Data Quality",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ds6",
        text: "Describe your experience with big data technologies.",
        category: "Big Data",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds7",
        text: "How do you communicate complex data insights to non-technical stakeholders?",
        category: "Communication",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ds8",
        text: "Tell me about a time when your model didn't perform as expected.",
        category: "Model Failure",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds9",
        text: "How do you approach feature engineering for machine learning models?",
        category: "Feature Engineering",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds10",
        text: "Describe your experience with different data visualization tools.",
        category: "Visualization",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ds11",
        text: "How do you ensure your models are ethical and unbiased?",
        category: "Ethics",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds12",
        text: "Tell me about your experience with A/B testing and statistical analysis.",
        category: "Statistics",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ds13",
        text: "How do you approach time series analysis and forecasting?",
        category: "Time Series",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds14",
        text: "Describe your experience with deep learning frameworks.",
        category: "Deep Learning",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ds15",
        text: "How do you stay updated with the latest developments in data science?",
        category: "Learning",
        difficulty: 2,
        thinkingTime: 45,
      },
    ],
  },
  {
    id: "ui-ux-designer",
    name: "UI/UX Designer",
    questions: [
      {
        id: "ux1",
        text: "How do you approach user research and what methods do you use?",
        category: "User Research",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux2",
        text: "Describe your design process from concept to final implementation.",
        category: "Design Process",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux3",
        text: "How do you balance user needs with business requirements?",
        category: "Balancing Priorities",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ux4",
        text: "Tell me about a time when you had to redesign an existing product.",
        category: "Redesign",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ux5",
        text: "How do you approach accessibility in your designs?",
        category: "Accessibility",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux6",
        text: "Describe your experience with design systems and component libraries.",
        category: "Design Systems",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux7",
        text: "How do you validate your design decisions with users?",
        category: "Design Validation",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux8",
        text: "Tell me about a time when you had to work within tight design constraints.",
        category: "Constraints",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ux9",
        text: "How do you approach mobile-first vs desktop-first design?",
        category: "Responsive Design",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux10",
        text: "Describe your experience with prototyping tools and methods.",
        category: "Prototyping",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux11",
        text: "How do you collaborate with developers to ensure design implementation?",
        category: "Developer Collaboration",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux12",
        text: "Tell me about a time when user feedback changed your design direction.",
        category: "Feedback Integration",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ux13",
        text: "How do you approach information architecture for complex applications?",
        category: "Information Architecture",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "ux14",
        text: "Describe your experience with data-driven design decisions.",
        category: "Data-Driven Design",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "ux15",
        text: "How do you stay updated with design trends and best practices?",
        category: "Design Trends",
        difficulty: 2,
        thinkingTime: 45,
      },
    ],
  },
  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    questions: [
      {
        id: "do1",
        text: "How do you approach infrastructure as code (IaC)?",
        category: "Infrastructure",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do2",
        text: "Describe your experience with containerization and orchestration.",
        category: "Containers",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "do3",
        text: "How do you implement and maintain CI/CD pipelines?",
        category: "CI/CD",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do4",
        text: "Tell me about a time when you had to handle a production incident.",
        category: "Incident Management",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do5",
        text: "How do you approach monitoring and observability in distributed systems?",
        category: "Monitoring",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do6",
        text: "Describe your experience with cloud platforms and services.",
        category: "Cloud Computing",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "do7",
        text: "How do you ensure security in your DevOps practices?",
        category: "Security",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do8",
        text: "Tell me about a time when you had to scale infrastructure rapidly.",
        category: "Scaling",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do9",
        text: "How do you approach configuration management?",
        category: "Configuration",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "do10",
        text: "Describe your experience with different automation tools.",
        category: "Automation",
        difficulty: 2,
        thinkingTime: 45,
      },
      {
        id: "do11",
        text: "How do you handle database migrations and deployments?",
        category: "Database Operations",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do12",
        text: "Tell me about a time when you had to optimize system performance.",
        category: "Performance Optimization",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do13",
        text: "How do you approach disaster recovery and backup strategies?",
        category: "Disaster Recovery",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do14",
        text: "Describe your experience with microservices architecture from an operations perspective.",
        category: "Microservices Operations",
        difficulty: 3,
        thinkingTime: 60,
      },
      {
        id: "do15",
        text: "How do you stay updated with new DevOps tools and practices?",
        category: "Learning",
        difficulty: 2,
        thinkingTime: 45,
      },
    ],
  },
];

// Re-export database functions as the main interface
export {
  getQuestionsForInterview,
  getAvailableFields,
} from "./questionDatabaseService";

// Export local questions as fallback (rename to avoid conflicts)
export const fallbackBehavioralQuestions = behavioralQuestions;
export const fallbackTechnicalQuestions = technicalQuestions;
export const fallbackLeadershipQuestions = leadershipQuestions;
export const fallbackCustomFields = customFields;
